###################  项目启动端口  ###################
####  swagger-ui的调试端口      http://localhost:8081/manager/docs.html
####  数据库连接池监控页面     http://localhost:8081/manager/druid/login.html
server:
  port: 8080
debug: true
spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://122.51.12.232:3306/taoke?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
      # 配置监控统计拦截的filters,去掉后，监控界面的sql无法统计
      filters: stat,wall,log4j
      dbcp2:
  　　    min-idle: 5         #数据库连接池的最小维持连接数
  　　    initial-size: 5     #初始化提供的连接数
  　　    max-total: 5          #最大的连接数
  　　    max-wait-millis: 200        #等待连接获取的最大超时时间
  http:
      converters:
          preferred-json-mapper: fastjson
  aop:
      proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理
  devtools:
      restart:
          enabled: true  #设置开启热部署
      freemarker:
          cache: false  # 页面不加缓存，修改及时生效
mybatis-plus:
  type-aliases-package: com.csz.entity
  mapperLocations: classpath*:com/csz/**/xml/*.xml
  global-config:
      id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
logging:
  level.root: info
  level.com.stylefeng: debug
  path: logs/
  file: manager.log



